"""notification_log_idempotency

Revision ID: 0a6846b7ba21
Revises: 7a86dbf71510
Create Date: 2026-07-21 23:45:24.128958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6846b7ba21'
down_revision = '7a86dbf71510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_logs', sa.Column('reference_type', sa.String(length=100), server_default='', nullable=False))
    op.add_column('notification_logs', sa.Column('reference_id', sa.String(length=255), server_default='', nullable=False))
    op.create_unique_constraint('uq_notification_logs_delivery', 'notification_logs', ['notification_type', 'reference_type', 'reference_id', 'channel', 'recipient'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_notification_logs_delivery', 'notification_logs', type_='unique')
    op.drop_column('notification_logs', 'reference_id')
    op.drop_column('notification_logs', 'reference_type')
    # ### end Alembic commands ###
