"""add fund website_url

Revision ID: 2fc15dadfdd0
Revises: 842395217b78
Create Date: 2026-07-23 13:17:22.895325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc15dadfdd0'
down_revision = '842395217b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('website_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'website_url')
    # ### end Alembic commands ###
