"""notification_log_idempotency

Revision ID: 0a6846b7ba21
Revises: 7a86dbf71510
Create Date: 2026-07-21 23:45:24.128958

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a6846b7ba21"
down_revision = "7a86dbf71510"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "notification_logs",
        sa.Column(
            "reference_type", sa.String(length=100), server_default="", nullable=False
        ),
    )
    op.add_column(
        "notification_logs",
        sa.Column(
            "reference_id", sa.String(length=255), server_default="", nullable=False
        ),
    )

    # Existing rows predate the reference columns, so they all backfill to
    # ('', ''). That collapses every historical row to the key
    # (notification_type, '', '', channel, recipient) — so any recipient who
    # ever received two notifications of the same type on the same channel
    # (e.g. two `customer.welcome` emails) becomes a duplicate and the
    # constraint below cannot be created.
    #
    # `notification_logs` is a delivery-audit log, not user-facing state, and
    # the historical rows carry no reference values that could disambiguate
    # them. We clear the table so the constraint can be created; from here on
    # every row is written with real reference values by
    # NotificationLogRepository.record_delivery.
    #
    # NOTE: this deliberately does NOT touch the `notifications` table — those
    # are the in-app rows users actually see, and they are unaffected by this
    # constraint.
    op.execute("DELETE FROM notification_logs")

    op.create_unique_constraint(
        "uq_notification_logs_delivery",
        "notification_logs",
        ["notification_type", "reference_type", "reference_id", "channel", "recipient"],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_notification_logs_delivery", "notification_logs", type_="unique"
    )
    op.drop_column("notification_logs", "reference_id")
    op.drop_column("notification_logs", "reference_type")
    # ### end Alembic commands ###
