"""drop funds current_size column

Revision ID: 7a86dbf71510
Revises: f6a7b8c9d0e1
Create Date: 2026-07-10 15:26:39.879628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a86dbf71510'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'current_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('current_size', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
