"""email_ingest_idempotency_and_draft_dedupe

Revision ID: 842395217b78
Revises: 6f03ef2aed6b
Create Date: 2026-07-22 00:43:36.258272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842395217b78'
down_revision = '6f03ef2aed6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_ingest_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.String(length=998), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_ingest_messages_message_id'), 'email_ingest_messages', ['message_id'], unique=True)
    op.add_column('communications', sa.Column('document_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_communications_document_id'), 'communications', ['document_id'], unique=False)
    op.create_foreign_key('communications_document_id_fkey', 'communications', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('communications_document_id_fkey', 'communications', type_='foreignkey')
    op.drop_index(op.f('ix_communications_document_id'), table_name='communications')
    op.drop_column('communications', 'document_id')
    op.drop_index(op.f('ix_email_ingest_messages_message_id'), table_name='email_ingest_messages')
    op.drop_table('email_ingest_messages')
    # ### end Alembic commands ###
