/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current User */
        get: operations["read_current_user_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Current User */
        patch: operations["update_current_user_users_me_patch"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        /** Invite User */
        post: operations["invite_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_users__user_id__patch"];
        trace?: never;
    };
    "/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User Role */
        patch: operations["update_user_role_users__user_id__role_patch"];
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Organizations */
        get: operations["list_organizations_organizations_get"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_organizations__organization_id__get"];
        put?: never;
        post?: never;
        /** Delete Organization */
        delete: operations["delete_organization_organizations__organization_id__delete"];
        options?: never;
        head?: never;
        /** Update Organization */
        patch: operations["update_organization_organizations__organization_id__patch"];
        trace?: never;
    };
    "/fund-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fund Groups */
        get: operations["list_fund_groups_fund_groups_get"];
        put?: never;
        /** Create Fund Group */
        post: operations["create_fund_group_fund_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fund-groups/{fund_group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fund Group */
        get: operations["get_fund_group_fund_groups__fund_group_id__get"];
        put?: never;
        post?: never;
        /** Delete Fund Group */
        delete: operations["delete_fund_group_fund_groups__fund_group_id__delete"];
        options?: never;
        head?: never;
        /** Update Fund Group */
        patch: operations["update_fund_group_fund_groups__fund_group_id__patch"];
        trace?: never;
    };
    "/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Funds */
        get: operations["list_funds_funds_get"];
        put?: never;
        /** Create Fund */
        post: operations["create_fund_funds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fund_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fund */
        get: operations["get_fund_funds__fund_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Fund */
        patch: operations["update_fund_funds__fund_id__patch"];
        trace?: never;
    };
    "/funds/{fund_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Fund */
        post: operations["archive_fund_funds__fund_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fund_id}/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Team Members */
        get: operations["list_team_members_funds__fund_id__team_get"];
        put?: never;
        /** Add Team Member */
        post: operations["add_team_member_funds__fund_id__team_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funds/{fund_id}/team/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Team Member */
        delete: operations["remove_team_member_funds__fund_id__team__member_id__delete"];
        options?: never;
        head?: never;
        /** Update Team Member */
        patch: operations["update_team_member_funds__fund_id__team__member_id__patch"];
        trace?: never;
    };
    "/investors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investors */
        get: operations["list_investors_investors_get"];
        put?: never;
        /** Create Investor */
        post: operations["create_investor_investors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investors/{investor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investor */
        get: operations["get_investor_investors__investor_id__get"];
        put?: never;
        post?: never;
        /** Delete Investor */
        delete: operations["delete_investor_investors__investor_id__delete"];
        options?: never;
        head?: never;
        /** Update Investor */
        patch: operations["update_investor_investors__investor_id__patch"];
        trace?: never;
    };
    "/investors/{investor_id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investor Contacts */
        get: operations["list_investor_contacts_investors__investor_id__contacts_get"];
        put?: never;
        /** Create Investor Contact */
        post: operations["create_investor_contact_investors__investor_id__contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investors/{investor_id}/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Investor Contact */
        delete: operations["delete_investor_contact_investors__investor_id__contacts__contact_id__delete"];
        options?: never;
        head?: never;
        /** Update Investor Contact */
        patch: operations["update_investor_contact_investors__investor_id__contacts__contact_id__patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CapitalCallStatus
         * @enum {string}
         */
        CapitalCallStatus: "draft" | "scheduled" | "sent" | "partially_paid" | "paid" | "overdue" | "cancelled";
        /** CapitalCallSummary */
        CapitalCallSummary: {
            /** Id */
            id: number;
            /** Fund Id */
            fund_id: number;
            /** Fund Name */
            fund_name: string;
            /** Title */
            title: string;
            /** Amount */
            amount: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            status: components["schemas"]["CapitalCallStatus"];
        };
        /** DashboardOverviewResponse */
        DashboardOverviewResponse: {
            /** Funds Active */
            funds_active: number;
            /** Investors Total */
            investors_total: number;
            /** Commitments Total Amount */
            commitments_total_amount: string;
            /** Capital Calls Outstanding */
            capital_calls_outstanding: number;
            /** Distributions Ytd Amount */
            distributions_ytd_amount: string;
            /** Recent Funds */
            recent_funds: components["schemas"]["FundSummary"][];
            /** Upcoming Capital Calls */
            upcoming_capital_calls: components["schemas"]["CapitalCallSummary"][];
        };
        /** FundCreate */
        FundCreate: {
            /** Organization Id */
            organization_id?: number | null;
            /** Fund Group Id */
            fund_group_id?: number | null;
            /** Name */
            name: string;
            /** Legal Name */
            legal_name?: string | null;
            /** Vintage Year */
            vintage_year?: number | null;
            /** Strategy */
            strategy?: string | null;
            /**
             * Currency Code
             * @default USD
             */
            currency_code: string;
            /** Target Size */
            target_size?: number | string | null;
            /** Hard Cap */
            hard_cap?: number | string | null;
            /** @default draft */
            status: components["schemas"]["FundStatus"];
            /** Inception Date */
            inception_date?: string | null;
            /** Close Date */
            close_date?: string | null;
            /** Description */
            description?: string | null;
        };
        /** FundGroupCreate */
        FundGroupCreate: {
            /** Organization Id */
            organization_id?: number | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** FundGroupRead */
        FundGroupRead: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Created By User Id */
            created_by_user_id: number | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** FundGroupUpdate */
        FundGroupUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** FundListItem */
        FundListItem: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Fund Group Id */
            fund_group_id: number | null;
            /** Name */
            name: string;
            /** Currency Code */
            currency_code: string;
            /** Target Size */
            target_size: string | null;
            /** Current Size */
            current_size: string;
            status: components["schemas"]["FundStatus"];
            /** Vintage Year */
            vintage_year: number | null;
        };
        /** FundRead */
        FundRead: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Fund Group Id */
            fund_group_id: number | null;
            /** Name */
            name: string;
            /** Legal Name */
            legal_name: string | null;
            /** Vintage Year */
            vintage_year: number | null;
            /** Strategy */
            strategy: string | null;
            /** Currency Code */
            currency_code: string;
            /** Target Size */
            target_size: string | null;
            /** Hard Cap */
            hard_cap: string | null;
            /** Current Size */
            current_size: string;
            status: components["schemas"]["FundStatus"];
            /** Inception Date */
            inception_date: string | null;
            /** Close Date */
            close_date: string | null;
            /** Description */
            description: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * FundStatus
         * @enum {string}
         */
        FundStatus: "draft" | "active" | "closed" | "liquidating" | "archived";
        /** FundSummary */
        FundSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Vintage Year */
            vintage_year?: number | null;
            /** Strategy */
            strategy?: string | null;
            status: components["schemas"]["FundStatus"];
            /** Currency Code */
            currency_code: string;
            /** Committed Amount */
            committed_amount: string;
            /** Called Amount */
            called_amount: string;
            /** Irr */
            irr?: string | null;
            /** Tvpi */
            tvpi?: string | null;
        };
        /** FundTeamMemberCreate */
        FundTeamMemberCreate: {
            /** User Id */
            user_id: number;
            /** Title */
            title?: string | null;
            /** Permissions */
            permissions?: string | null;
        };
        /** FundTeamMemberRead */
        FundTeamMemberRead: {
            /** Id */
            id: number;
            /** Fund Id */
            fund_id: number;
            /** User Id */
            user_id: number;
            /** Title */
            title: string | null;
            /** Permissions */
            permissions: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** FundTeamMemberUpdate */
        FundTeamMemberUpdate: {
            /** Title */
            title?: string | null;
            /** Permissions */
            permissions?: string | null;
        };
        /** FundUpdate */
        FundUpdate: {
            /** Fund Group Id */
            fund_group_id?: number | null;
            /** Name */
            name?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Vintage Year */
            vintage_year?: number | null;
            /** Strategy */
            strategy?: string | null;
            /** Currency Code */
            currency_code?: string | null;
            /** Target Size */
            target_size?: number | string | null;
            /** Hard Cap */
            hard_cap?: number | string | null;
            status?: components["schemas"]["FundStatus"] | null;
            /** Inception Date */
            inception_date?: string | null;
            /** Close Date */
            close_date?: string | null;
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestorContactCreate */
        InvestorContactCreate: {
            /** User Id */
            user_id?: number | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Title */
            title?: string | null;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean | null;
        };
        /** InvestorContactRead */
        InvestorContactRead: {
            /** Id */
            id: number;
            /** Investor Id */
            investor_id: number;
            /** User Id */
            user_id: number | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Title */
            title: string | null;
            /** Is Primary */
            is_primary: boolean | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** InvestorContactUpdate */
        InvestorContactUpdate: {
            /** User Id */
            user_id?: number | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Title */
            title?: string | null;
            /** Is Primary */
            is_primary?: boolean | null;
        };
        /** InvestorCreate */
        InvestorCreate: {
            /** Organization Id */
            organization_id?: number | null;
            /** Investor Code */
            investor_code?: string | null;
            /** Name */
            name: string;
            /** Investor Type */
            investor_type?: string | null;
            /**
             * Accredited
             * @default false
             */
            accredited: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** InvestorListItem */
        InvestorListItem: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Investor Code */
            investor_code: string | null;
            /** Name */
            name: string;
            /** Investor Type */
            investor_type: string | null;
            /** Accredited */
            accredited: boolean | null;
            /** Total Committed */
            total_committed: string;
            /** Fund Count */
            fund_count: number;
        };
        /** InvestorRead */
        InvestorRead: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number;
            /** Investor Code */
            investor_code: string | null;
            /** Name */
            name: string;
            /** Investor Type */
            investor_type: string | null;
            /** Accredited */
            accredited: boolean | null;
            /** Notes */
            notes: string | null;
            /** Total Committed */
            total_committed: string;
            /** Fund Count */
            fund_count: number;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** InvestorUpdate */
        InvestorUpdate: {
            /** Investor Code */
            investor_code?: string | null;
            /** Name */
            name?: string | null;
            /** Investor Type */
            investor_type?: string | null;
            /** Accredited */
            accredited?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** OrganizationCreate */
        OrganizationCreate: {
            type: components["schemas"]["OrganizationType"];
            /** Name */
            name: string;
            /** Legal Name */
            legal_name?: string | null;
            /** Tax Id */
            tax_id?: string | null;
            /** Website */
            website?: string | null;
            /** Description */
            description?: string | null;
        };
        /** OrganizationRead */
        OrganizationRead: {
            /** Id */
            id: number;
            type: components["schemas"]["OrganizationType"];
            /** Name */
            name: string;
            /** Legal Name */
            legal_name: string | null;
            /** Tax Id */
            tax_id: string | null;
            /** Website */
            website: string | null;
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * OrganizationType
         * @enum {string}
         */
        OrganizationType: "fund_manager_firm" | "investor_firm" | "service_provider";
        /** OrganizationUpdate */
        OrganizationUpdate: {
            type?: components["schemas"]["OrganizationType"] | null;
            /** Name */
            name?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Tax Id */
            tax_id?: string | null;
            /** Website */
            website?: string | null;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Organization Id */
            organization_id?: number | null;
            role: components["schemas"]["UserRole"];
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Title */
            title?: string | null;
            /** Hanko Subject Id */
            hanko_subject_id?: string | null;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Organization Id */
            organization_id: number | null;
            role: components["schemas"]["UserRole"];
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string | null;
            /** Title */
            title: string | null;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /** Hanko Subject Id */
            hanko_subject_id: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "fund_manager" | "lp";
        /** UserRoleUpdate */
        UserRoleUpdate: {
            role: components["schemas"]["UserRole"];
        };
        /** UserSelfUpdate */
        UserSelfUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Title */
            title?: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Title */
            title?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_overview_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverviewResponse"];
                };
            };
        };
    };
    read_current_user_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_current_user_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSelfUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_role_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organizations_organizations_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_organizations__organization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_organization_organizations__organization_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization_organizations__organization_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fund_groups_fund_groups_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundGroupRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fund_group_fund_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fund_group_fund_groups__fund_group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fund_group_fund_groups__fund_group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fund_group_fund_groups__fund_group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_funds_funds_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fund_funds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fund_funds__fund_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fund_funds__fund_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_fund_funds__fund_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_members_funds__fund_id__team_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                fund_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundTeamMemberRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_team_member_funds__fund_id__team_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundTeamMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundTeamMemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_team_member_funds__fund_id__team__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_id: number;
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundTeamMemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_member_funds__fund_id__team__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fund_id: number;
                member_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundTeamMemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundTeamMemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investors_investors_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investor_investors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investor_investors__investor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_investor_investors__investor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investor_investors__investor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investor_contacts_investors__investor_id__contacts_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorContactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investor_contact_investors__investor_id__contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorContactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_investor_contact_investors__investor_id__contacts__contact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorContactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investor_contact_investors__investor_id__contacts__contact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investor_id: number;
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorContactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorContactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
